### ISSUE TITLE
Incorrect syntax highlight

### ISSUE THREAD

**Issue by escaton** [silvenon/vscode-mdx#12]
Sometimes links highlighting are broken if there are some jsx above
![изображение](https://user-images.githubusercontent.com/2072871/66773346-804ddd80-eec7-11e9-9bb8-fbbbd27c9aae.png)

![изображение](https://user-images.githubusercontent.com/2072871/66773611-13871300-eec8-11e9-9a54-1b68108a7aac.png)

**Comment by silvenon** [comment]
Could you please confirm whether this is still an issue for you? It doesn't appear to be anymore.

<img width="600" alt="Screenshot 2020-01-22 at 21 08 58" src="https://user-images.githubusercontent.com/471278/72930065-6b50d800-3d5b-11ea-933d-b530fe59a6aa.png">
