### ISSUE TITLE
Highlighting broken by word 'for'

### ISSUE THREAD

**Issue by Undistraction** [silvenon/vscode-mdx#13]
<img width="632" alt="Screenshot 2019-10-23 at 16 55 46" src="https://user-images.githubusercontent.com/161489/67411766-0c41c280-f5b6-11e9-8ac8-02cdcdc805d5.png">

```
import Button from './Button'
import { Meta, Story, Props } from '@storybook/addon-docs/blocks'

<Meta title="Button" component={Button} />

# Button

With 'MDX' we write longform markdown documentation for our 'Button' component and embed Doc Blocks inline.

<Props of={Button} />

<Story name="positive">
  <Button>Button</Button>
</Story>
```

**Comment by silvenon** [comment]
This doesn't seem to be an issue, at least not anymore.

<img width="662" alt="Screenshot 2020-01-22 at 21 10 08" src="https://user-images.githubusercontent.com/471278/72930132-9509ff00-3d5b-11ea-95ff-173dfc835a6e.png">

If you're still experiencing this, ensure that the file is indeed using the MDX grammar and share more details. Thanks!
