### ISSUE TITLE
Highlighting broken by close brace

### ISSUE THREAD

**Issue by Danielku15** [silvenon/vscode-mdx#15]
It seems that the highlighting is broken on certain close brace characters. Here some example scenarios that show the issue: 

![image](https://user-images.githubusercontent.com/674916/76143378-45676480-6077-11ea-86e9-5fec270bc05c.png)

This makes it a bit unfortunate to use the extension if you have functions and classes in your MDX. I am using version 0.1.0 from the marketplace.

**Comment by Danielku15** [comment]
Update: Sorry. It seems rather to be an issue in MDX in general that it does not support JSX properly. In all parts where the highlighting is broken, the MDX compiler also complains even though the syntax is valid JSX. 

For those who run into similar issues, here some background: 
The actual issue was that MDX does not yet support empty lines. The JSX blocks are interrupted on empty lines. The related improvement issue on MDX side to this is https://github.com/mdx-js/mdx/issues/195

**Comment by silvenon** [comment]
Thanks for taking the time to close this issue after you verified that this shouldn't be supported yet. Feel free to reopen when MDX starts supporting this.
