### ISSUE TITLE
Preserve VS code's soft word wrap

### ISSUE THREAD

**Issue by gaelhameon** [silvenon/vscode-mdx#18]
Hi !

Thanks for the extension!

I was wondering if there is a way to preserve the word wrap settings when activating this extension.

I have these settings:

```
    "[markdown]": {
        "editor.wordWrap": "wordWrapColumn",
        "editor.wordWrapColumn": 100,
    },
```
which give me this result when writing long text in markdown:
![image](https://user-images.githubusercontent.com/17253950/99158771-ca128400-26d6-11eb-836d-99afd51fb620.png)

But if I activate the extension, I get the result below, which is a little harder to work with ...

![image](https://user-images.githubusercontent.com/17253950/99158812-473df900-26d7-11eb-9b93-ba25b1c65430.png)

**Comment by silvenon** [comment]
What about this?

```
"[mdx]": {
  "editor.wordWrap": "wordWrapColumn",
  "editor.wordWrapColumn": 100,
},
```

**Comment by gaelhameon** [comment]
Yes, perfect! Thank you !
I suggested a readme update in case you think it's worth it. But I totally get it too if you don't want the readme to get too bloated.
Thanks again!

**Comment by silvenon** [comment]
It's great, I think it will help others, thanks 😃
