### ISSUE TITLE
Default syntax highlighting

### ISSUE THREAD

**Issue by silverqx** [silvenon/vscode-mdx#25]
Is it possible to set a default syntax highlighting for code blocks?

I have something like this in my `Docusaurus` config:
```
    prism: {
      theme: lightCodeTheme,
      darkTheme: darkCodeTheme,
      defaultLanguage: 'cpp',
      additionalLanguages: ['cmake', 'powershell'],
    },
```

So when I have some code block in my MDX document intended by 4 spaces then it is automatically highlighted as the cpp code block.

But these code blocks are not highlighted in the `vscode` editor. 😞

Currently, if I want to have also syntax highlighting in the `vscode` editor I have to be explicit and I have to provide ` ```cpp`.

Would be really helpful to be able to provide a default syntax highlighting to the `vscode-mdx` extension.

**Comment by silvenon** [comment]
Hey Silver, not any time soon, I'm not developing this extension currently. But even so, I'm worried that it would be pretty odd to offer default language to anyone who is not in your particular situation. It's not a common practice to want to have a default language, in my blog posts I sometimes want code blocks that show stuff like file structure, so I don't want them to have a language.

**Comment by silverqx** [comment]
Ok, thx for the reply, the reason for this is of course to avoid a lot of mess around code blocks, to have the documentation more clear. 
If I have to choose between 4 indents without syntax highlighting or ` ```cpp` tags around every block with syntax highlighting then I'm choosing 4 indents 😎.

If you don't plan to implement this in the future then we can close this issue, thx.

**Comment by silvenon** [comment]
What I'm doing it this extension is fairly simple, basically I'm telling VS Code when to switch to Markdown language, when to switch to JSX etc. (Now with MDX v2 this VS Code is not doing good enough of a job anymore.) So if you want to bring this into MDX your best course of action would be to try to get this into VS Code's _Markdown_ language because this feature is Markdown-specific, not MDX 🙂 

Sorry about closing your issue, I think your use case is cool!

**Comment by silverqx** [comment]
You are right, when I'm thinking about it then the vscode markdown extension is responsible for this, he decides which syntax highlighter will be used, this extension only provides mdx part (whatever it means).
That means that reporting this issue to the vscode is like one drop of water during rain 😏 I don't even try it, the wait time could be years 😎

**Comment by silvenon** [comment]
Yeah, I totally understand why you feel that way. Maybe it would be possible to create a separate extension that would extend the Markdown language? 🤔  I don't know enough about extending VS Code to be able to say for sure (I barely know anything 😅 ), but maybe you could give it a shot.
