### ISSUE TITLE
Deprecate this extension in case we have `unifiedjs.vscode-mdx` now?

### ISSUE THREAD

**Issue by JounQin** [silvenon/vscode-mdx#26]
I've just migrate from `JounQin.vscode-mdx` to [`unifiedjs.vscode-mdx`](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx) successfully via https://github.com/microsoft/vsmarketplace/issues/440.

**Comment by silvenon** [comment]
I'd like to, yes, I posted https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-3340102 asking them to deprecate it. Is there something else you think I should do? Update the readme maybe?

**Comment by JounQin** [comment]
> Is there something else you think I should do? Update the readme maybe?

I think it's the action, HDYT?

**Comment by JounQin** [comment]
Like https://marketplace.visualstudio.com/items?itemName=balajmarius.vscode-deprecated, it also adds a deprecated suffix in its display name.

**Comment by silvenon** [comment]
I think that extension has the "deprecated" suffix because it's checking for deprecated imports, not because the extension itself is deprecated.

> I think it's the action

What do you mean by this? Please elaborate what exactly you think should be done 🙏

**Comment by JounQin** [comment]
> I think that extension has the "deprecated" suffix because it's checking for deprecated imports, not because the extension itself is deprecated.

Ah, sorry, I misread that. But the `Deprcated` suffix is also meaningful in our situation.

> What do you mean by this? Please elaborate what exactly you think should be done 🙏

I'm sorry if I make you confused.

I mean:

1. add deprecated notice into README
2. publish a new version with ` (Deprcated)` suffix in the `displayName` like [TSLint (deprecated)](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) or [[Deprecated] Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)

HDYT?

**Comment by silvenon** [comment]
Done! ✅

**Comment by waldyrious** [comment]
> Done! :white_check_mark:

For reference, the changes were implemented in commit c68ac445814d472b7120cb706f5f64d8c33bdfe1.

Also, cross-linking #21 for further context.

**Comment by silvenon** [comment]
Thanks!
