### ISSUE TITLE
Suggestion: Add link to vscode extension marketplace / install snippet to Readme

### ISSUE THREAD

**Issue by hamlim** [silvenon/vscode-mdx#3]
First off thanks for making this vscode extension!

After I found this repo, it took me a while to track down the name of the extension that I needed to install. I think it would be beneficial to others to add a link to the marketplace (https://marketplace.visualstudio.com/) from the Readme to make it a bit easier to install the extension.

### Suggested Changes:

Adding this to the Readme:

```md
### Installation

You can install this extension from [here](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx).
```

**Comment by silvenon** [comment]
Done, thanks!
