### ISSUE TITLE
Auto-enclose word with backticks

### ISSUE THREAD

**Issue by nikolasburk** [silvenon/vscode-mdx#4]
When using regular markdown files in VS Code, I can:

1. Select a word
1. Hit the backtick key: `
1. Result: The entire word is enclosed with backticks, so instead of manually putting the cursor to the word's beginning and end and hit the backtick key each time, I can just hit it once when the word is selected.

Would be awesome if this was supported by the MDX extension as well.

(Side-note: I'm a big fan of the extension, thanks a lot for your awesome work @silvenon)

**Comment by silvenon** [comment]
Done! It will be available in the next release (not published yet).

I'm glad you enjoy the extension! Keep the feedback coming 😉

**Comment by nikolasburk** [comment]
Wow thanks so much! 🙏  I'm using a lot of MDX in my daily workflows so I'll surely come up with more ideas to improve the extension 🙌

**Comment by silvenon** [comment]
Published in 0.1.0!
